# general settings
# name: ennet_tower # doesn't matter, only file name matters
model_type: ImageCleanModel 
scale: 1
# num_gpu: 1  # set num_gpu: 0 for cpu mode
# device: "0" # 需为单个数字

manual_seed: 42

ensemble_models: ['retinexformer', 'cidnet', 'glare', 'flw', 'lmt'] # 'retinexformer', 'cidnet', 'glare', 'lytnet', 'flw', 'lmt'
dataset_name: LOLv2s
# weight_path: pretrained_weights/best_psnr_26.95_25000.pth


# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: /root/autodl-tmp/ennet/datasets/LOLv2/Synthetic/Train/Normal
    dataroot_lq: /root/autodl-tmp/ennet/datasets/LOLv2/Synthetic/Train/Low
    geometric_augs: true # 开启几何数据增强
    filename_tmpl: '{}' # Template for each filename.
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 0
    batch_size_per_gpu: 4 # 
    # iters: [100000]
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    # pin_memory: true 将加载的数据张量固定在CPU内存中以提速，但需要cpu内存足够
    ### -------------Progressive training---------------------------
    mini_batch_sizes: [4,2,1]
    iters: [10000,10000,10000]
    # gt_size: 384   # Max patch size for progressive training
    # gt_sizes: [128,160,192,256,320,384]  # Patch sizes for progressive training.
    # ### ------------------------------------------------------------

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: /root/autodl-tmp/ennet/datasets/LOLv2/Synthetic/Test/Normal
    dataroot_lq: /root/autodl-tmp/ennet/datasets/LOLv2/Synthetic/Test/Low
    io_backend:
      type: disk

# network structures
network_g:
  type: Ennet  # network name, in basicsr/models/archs/
  block_size: 16
  stride: 8
  emb_dim: 64
  n_layers: 2
  # 5.5e5


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# 训练设置
train:
  total_iter: 30000
  warmup_iter: -1 # no warm up
  use_grad_clip: true
  lambda_moe: !!float 0.5

  scheduler: # 学习率调整
    type: CosineAnnealingRestartCyclicLR # 带重启的余弦退火学习率调度
    periods: [20000, 10000]  # 每个余弦退火周期的持续时间
    restart_weights: [1,1] # 每次重启时的学习率权重
    eta_mins: [0.0002, 0.00001] # 每个周期的最小学习率值
  
  mixing_augs: # 混合增强
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g: # 优化器设置
    type: Adam
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  pixel_opt: # losses
    type: L1Loss
    loss_weight: 1
    reduction: mean


# validation settings
val:
  # window_size: 4
  val_freq: !!float 3000
  save_img: true
  rgb2bgr: true
  use_image: true # ????
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
    ssim: 
      type: calculate_ssim
    lpips: 
      type: calculate_lpips

# logging settings
logger:
  print_freq: 100 #打印日志
  save_checkpoint_freq: 5000 
  use_tb_logger: true
  wandb:
    project: low_light
    resume_id: ~
